version: '3.8'

services:
  api-dbpostgres:
    container_name: db-pg-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin-compose:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5049:80"
    depends_on:
      - api-dbpostgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge